# This is a basic workflow to help you get started with Actions

name: Pack to Powershell Gallery

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Publish-Module -Path .\Module -NuGetApiKey $env:NUGET_KEY -Verbose
