# This is a basic workflow to help you get started with Actions

name: Pack to Powershell Gallery

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Publishing
        working-directory: .
        env:
         NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          import-module PowerShellGet
          $Version=Find-Module -Name FoxHelper | Where-Object -Property Repository -EQ PSGallery |Select-Object -ExpandProperty Version
          $Revision=($Version.Revision)+1
          [string]$Version=$Version
          $Version=$Version.Substring(0, $Version.lastIndexOf('.'))
          $Version=$Version + '.' + $Revision
          Update-Manifest -Path '/home/runner/work/FoxHelper/FoxHelper/FoxHelper/FoxHelper.psd1' -PropertyName ModuleVersion  -Value $Version
          Publish-Module -Path /home/runner/work/FoxHelper/FoxHelper/FoxHelper  -NuGetApiKey $env:NUGET_KEY -verbos
        shell: pwsh
